
# IMDB title_basics data cleaning
#Reference https://datasets.imdbws.com/
```{r}
imdb_tb <- read.delim(gzfile("data/imdb/title.basics.tsv.gz"))

imdb_movies <- imdb_tb[imdb_tb$titleType == "movie", ]
imdb_movies <- imdb_movies[imdb_movies$isAdult == 0, ]
imdb_movies <- imdb_movies[imdb_movies$genres != "\\N",]
imdb_movies$isAdult = NULL
imdb_movies$endYear = NULL
imdb_movies$runtimeMinutes = NULL
imdb_movies$titleType = NULL

write.csv(imdb_movies, "data/imdb/movies.csv")
```

# Oscars cleaning 
#Reference https://www.kaggle.com/theacademy/academy-awards
```{r}

oscars <- read.csv("data/oscars/database.csv")


best_pictures <- na.omit(oscars[(oscars$Award == "Best Picture" | 
                                 oscars$Award == "Outstanding Picture" |
                                 oscars$Award == "Outstanding Production" |
                                 oscars$Award == "Outstanding Motion Picture" |
                                 oscars$Award == "Best Motion Picture")
                                & oscars$Winner == 1,], col = oscars$Winner)

years <- levels(best_pictures$Year)   
years[1] = "1928"
years[2] = "1929"
years[3] = "1930"
years[4] = "1931"
years[5] = "1932"
years[6] = "1933"
levels(best_pictures$Year) = factor(years)
best_pictures$Winner = NULL

names <- levels(best_pictures$Name)
names[names == "Metro-Goldwyn-Mayer"] = "The Broadway Melody"
names[names == "Paramount Famous Lasky"] = "Wings"
names <- trimws(names, which = c("both", "left", "right"))
levels(best_pictures$Name) = factor(names)

films <- levels(best_pictures$Film)
films[films == "Wings"] = "Paramount Famous Lasky"
films[films == "The Broadway Melody"] = "Metro-Goldwyn-Mayer"
films <- trimws(films, which = c("both", "left", "right"))
levels(best_pictures$Film) = factor(films)


write.csv(best_pictures, "data/oscars/best_pictures.csv")
```

# Connect oscars best pictures data to IMDB data 
```{r}

imdb_movies <- read.csv("data/imdb/movies.csv")
titles <- levels(imdb_movies$primaryTitle) 
titles <- trimws(titles, which = c("both", "left", "right"))
levels(imdb_movies$primaryTitle) = factor(titles)

oscars_ratings <- merge(x = best_pictures, y = imdb_movies, 
                        by.x = c("Name", "Year"), by.y = c("primaryTitle", "startYear"),  all.x = TRUE)

oscars_ratings$tconst[which(oscars_ratings$Name == "Wings")] = "tt0018578"
oscars_ratings$tconst[which(oscars_ratings$Name == "Casablanca")] = "tt0034583"
oscars_ratings$tconst[which(oscars_ratings$Name == "All about Eve")] = "tt0042192"
oscars_ratings$tconst[which(oscars_ratings$Name == "MA*S*H")] = "tt0066026"
oscars_ratings$tconst[which(oscars_ratings$Name == "The Godfather Part II")] = "tt0071562"
oscars_ratings$tconst[which(oscars_ratings$Name == "One Flew over the Cuckoo's Nest")] = "tt0073486"
oscars_ratings$tconst[which(oscars_ratings$Name == "Dances With Wolves")] = "tt0099348"
oscars_ratings$tconst[which(oscars_ratings$Name == "Crash")] = "tt0375679"
oscars_ratings$tconst[which(oscars_ratings$Name == "The Hurt Locker")] = "tt0887912"



oscars_ratings <- merge(x = oscars_ratings, y = imdb_movies, 
                        by = "tconst", all.x = TRUE)
colnames(oscars_ratings)[which(colnames(oscars_ratings) == "genres.y")] = "genres"
oscars_ratings <- subset(oscars_ratings, select = c("tconst", "Name", "Year", "Film", "genres"))
write.csv(oscars_ratings, "data/oscars/best_pictures.csv")
```

